# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Pascal Bugnion
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-sql
project_short_description: JupyterLab extension for interacting with SQL databases
python_name: jupyterlab_sql
repository: github.com/pbugnion/jupyterlab-sql.git
test: true

